apiVersion: v1
kind: Service
metadata:
  name: spring-config-prod
  namespace: spring-boot-examples
spec:
  ports:
    - name: config-demo
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: config-demo-prod
  type: ClusterIP
#type: NodePort