example:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.200:1521:cdb1
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: SYSTEM
    password: dudkrish1A
    jpa:
      show-sql: true
      format-sql: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.Oracle12cDialect

---
spring:
  config:
    activate:
      on-profile: dev 
  datasource:
    url: ${example.datasource.url}
    username: ${example.datasource.username}
    password: ${example.datasource.password}
---
spring:
  config:
    activate:
      on-profile: pre-prod
  datasource:
    url: ${example.datasource.url}
    username: ${example.datasource.username}
    password: ${example.datasource.password}
